import type { Workspace } from '../../shared/types';
type TFunctionLike = (key: string, defaultValue: string) => string;
type WorkspaceKindLike = Pick<Workspace, 'kind'>;
type WorkspaceProtectedLike = Pick<Workspace, 'kind' | 'isProtected'>;
type WorkspaceDisplayLike = Pick<Workspace, 'name' | 'kind' | 'isProtected'>;
export declare function isConversationWorkspace(workspace: WorkspaceKindLike | null | undefined): boolean;
export declare function isProtectedWorkspace(workspace: WorkspaceProtectedLike | null | undefined): boolean;
export declare function getWorkspaceDisplayName(workspace: WorkspaceDisplayLike | null | undefined, t: TFunctionLike): string;
export declare function getWorkspaceInitial(workspace: WorkspaceDisplayLike | null | undefined, t: TFunctionLike): string;
export {};
