/**
 * HopCode Backend (ACP SDK Client)
 *
 * Spawns HopCode in ACP mode and adapts ACP session updates into Craft's
 * provider-agnostic AgentEvent stream.
 */
import type { AgentEvent } from '@craft-agent/core/types';
import type { FileAttachment } from '../utils/files.ts';
import type { ModelFetchResult } from '../config/model-fetcher.ts';
import { BaseAgent } from './base-agent.ts';
import type { BackendConfig, BackendSessionMessagesResult, AvailableCommandsSnapshot, BackendSessionListOptions, BackendSessionListResult, BackendRewindResult, ChatOptions, BackendHostRuntimeContext, MidTurnMessageMetadata, SdkMcpServerConfig } from './backend/types.ts';
import { AbortReason } from './backend/types.ts';
import type { PermissionMode } from './mode-manager.ts';
import { type LLMQueryRequest, type LLMQueryResult } from './llm-tool.ts';
import type { PermissionResponseOptions, PermissionRuleType, PermissionSettingsScope, HopCodeCoreSettingKey, HopCodeCoreSettingsSnapshot, HopCodeHookDefinition, HopCodeHookEvent, HopCodeMcpServerConfig, HopCodePermissionSettings, HopCodeProviderCatalog, HopCodeProviderConnectParams, HopCodeProviderConnectResult, HopCodeSettingValue, HopCodeSettingsScope, HopCodeSkillDeleteRequest, HopCodeSkillDeleteResult, HopCodeSkillInstallRequest, HopCodeSkillInstallResult, HopCodeSkillSetEnabledRequest, HopCodeSkillSetEnabledResult } from '../protocol/dto.ts';
import type { HopCodeMemoryPaths, HopCodeMemorySettings } from '../config/hopcode-settings.ts';
export declare function formatHopCodeAcpErrorMessage(error: unknown): string;
type HopCodeSettingsAcpOptions = {
    hostRuntime: BackendHostRuntimeContext;
    cwd?: string;
    processCwd?: string;
    envOverrides?: Record<string, string>;
    timeoutMs?: number;
    debug?: (message: string) => void;
};
export declare function getHopCodeMemorySettingsViaAcp(options: HopCodeSettingsAcpOptions): Promise<HopCodeMemorySettings>;
export declare function setHopCodeMemorySettingsViaAcp(options: HopCodeSettingsAcpOptions, updates: Partial<HopCodeMemorySettings>): Promise<HopCodeMemorySettings>;
export declare function getHopCodeSettingsPathViaAcp(options: HopCodeSettingsAcpOptions): Promise<string>;
export declare function getHopCodeCoreSettingsViaAcp(options: HopCodeSettingsAcpOptions): Promise<HopCodeCoreSettingsSnapshot>;
export declare function setHopCodeCoreSettingViaAcp(options: HopCodeSettingsAcpOptions, scope: HopCodeSettingsScope, key: HopCodeCoreSettingKey, value: HopCodeSettingValue): Promise<HopCodeCoreSettingsSnapshot>;
export declare function setHopCodeMcpServerViaAcp(options: HopCodeSettingsAcpOptions, scope: HopCodeSettingsScope, name: string, server: HopCodeMcpServerConfig): Promise<HopCodeCoreSettingsSnapshot>;
export declare function removeHopCodeMcpServerViaAcp(options: HopCodeSettingsAcpOptions, scope: HopCodeSettingsScope, name: string): Promise<HopCodeCoreSettingsSnapshot>;
export declare function setHopCodeHookViaAcp(options: HopCodeSettingsAcpOptions, scope: HopCodeSettingsScope, event: HopCodeHookEvent, index: number | undefined, hook: HopCodeHookDefinition): Promise<HopCodeCoreSettingsSnapshot>;
export declare function removeHopCodeHookViaAcp(options: HopCodeSettingsAcpOptions, scope: HopCodeSettingsScope, event: HopCodeHookEvent, index: number): Promise<HopCodeCoreSettingsSnapshot>;
export declare function setHopCodeExtensionSettingViaAcp(options: HopCodeSettingsAcpOptions, extensionId: string, settingKey: string, scope: HopCodeSettingsScope, value: HopCodeSettingValue): Promise<HopCodeCoreSettingsSnapshot>;
export declare function getHopCodePermissionSettingsViaAcp(options: HopCodeSettingsAcpOptions): Promise<HopCodePermissionSettings>;
export declare function setHopCodePermissionRulesViaAcp(options: HopCodeSettingsAcpOptions, scope: PermissionSettingsScope, ruleType: PermissionRuleType, rules: string[]): Promise<HopCodePermissionSettings>;
export declare function getHopCodeMemoryPathsViaAcp(options: HopCodeSettingsAcpOptions & {
    projectRoot?: string;
}): Promise<HopCodeMemoryPaths>;
export declare function listHopCodeProvidersViaAcp(options: HopCodeSettingsAcpOptions): Promise<HopCodeProviderCatalog>;
export declare function getHopCodeWorkspacePreflightViaAcp(options: HopCodeSettingsAcpOptions): Promise<Record<string, unknown>>;
export declare function fetchHopCodeModelsViaSharedAcp(options: HopCodeSettingsAcpOptions): Promise<ModelFetchResult>;
export declare function connectHopCodeProviderViaAcp(options: HopCodeSettingsAcpOptions, params: HopCodeProviderConnectParams): Promise<HopCodeProviderConnectResult>;
export declare function extractHopCodeParentToolUseId(update: Record<string, unknown>): string | undefined;
export declare function resolveHopCodeParentToolUseId(args: {
    update: Record<string, unknown>;
    toolUseId?: string;
    activeParentToolUseIds?: ReadonlySet<string>;
}): string | undefined;
export declare class HopCodeAgent extends BaseAgent {
    protected backendName: string;
    private acpLease;
    private connection;
    private hopcodeSessionId;
    private ensureHopCodeSessionPromise;
    private eventQueue;
    private _isProcessing;
    private abortReason?;
    private persistedHopCodeSessionId;
    private activePromptRunId;
    private promptRunCounter;
    private permissionRequestCounter;
    private toolIdCounter;
    private planUpdateCounter;
    private hasInitialModeOverride;
    private pendingModeOverride;
    private pendingPermissions;
    private miniCollectors;
    private historyCollectors;
    private ensureProcessPromise;
    private suppressedSessionUpdates;
    private pendingAvailableCommandsUpdates;
    private latestAvailableCommandsSnapshot;
    private availableCommandsWaiters;
    private availableModelIds;
    private availableModelsById;
    private firstAvailableModelId;
    private sourceMcpServers;
    private currentTurnId;
    private currentAssistantText;
    private currentThoughtText;
    private currentAssistantParentToolUseId;
    private currentThoughtParentToolUseId;
    private currentIsSlashCommand;
    private capturedUsageInCurrentTurn;
    private usageWaiters;
    private toolNames;
    private toolInputs;
    private activeParentToolUseIds;
    private midTurnMessageQueue;
    constructor(config: BackendConfig);
    getRecentStderr(): string;
    getSessionId(): string | null;
    setSessionId(sessionId: string | null): void;
    clearHistory(): void;
    protected extractSkillPaths(message: string): {
        skillPaths: Map<string, string>;
        cleanMessage: string;
        missingSkills: string[];
    };
    updateWorkingDirectory(path: string): void;
    private invalidateAvailableCommandsSnapshot;
    protected chatImpl(messageParam: string, attachments?: FileAttachment[], options?: ChatOptions): AsyncGenerator<AgentEvent>;
    isProcessing(): boolean;
    private waitForCurrentTurnUsage;
    private resolveUsageWaiters;
    enqueueMidTurnMessage(message: string, attachments?: FileAttachment[], metadata?: MidTurnMessageMetadata): boolean;
    abort(reason?: string): Promise<void>;
    forceAbort(reason: AbortReason): void;
    respondToPermission(requestId: string, allowed: boolean, alwaysAllow?: boolean, options?: PermissionResponseOptions): void;
    setPermissionMode(mode: PermissionMode): void;
    cyclePermissionMode(): PermissionMode;
    getPermissionSettings(): Promise<HopCodePermissionSettings>;
    setPermissionRules(scope: PermissionSettingsScope, ruleType: PermissionRuleType, rules: string[]): Promise<HopCodePermissionSettings>;
    getCoreSettings(): Promise<HopCodeCoreSettingsSnapshot>;
    listProviders(): Promise<HopCodeProviderCatalog>;
    connectProvider(params: HopCodeProviderConnectParams): Promise<HopCodeProviderConnectResult>;
    setCoreSetting(scope: HopCodeSettingsScope, key: HopCodeCoreSettingKey, value: HopCodeSettingValue): Promise<HopCodeCoreSettingsSnapshot>;
    setMcpServer(scope: HopCodeSettingsScope, name: string, server: HopCodeMcpServerConfig): Promise<HopCodeCoreSettingsSnapshot>;
    removeMcpServer(scope: HopCodeSettingsScope, name: string): Promise<HopCodeCoreSettingsSnapshot>;
    setHook(scope: HopCodeSettingsScope, event: HopCodeHookEvent, index: number | undefined, hook: HopCodeHookDefinition): Promise<HopCodeCoreSettingsSnapshot>;
    removeHook(scope: HopCodeSettingsScope, event: HopCodeHookEvent, index: number): Promise<HopCodeCoreSettingsSnapshot>;
    setExtensionSetting(extensionId: string, settingKey: string, scope: HopCodeSettingsScope, value: HopCodeSettingValue): Promise<HopCodeCoreSettingsSnapshot>;
    installSkill(request: HopCodeSkillInstallRequest): Promise<HopCodeSkillInstallResult>;
    deleteSkill(request: HopCodeSkillDeleteRequest): Promise<HopCodeSkillDeleteResult>;
    setSkillEnabled(request: HopCodeSkillSetEnabledRequest): Promise<HopCodeSkillSetEnabledResult>;
    setModel(model: string): void;
    setSourceServers(mcpServers: Record<string, SdkMcpServerConfig>, apiServers: Record<string, unknown>, intendedSlugs?: string[]): Promise<void>;
    runMiniCompletion(prompt: string): Promise<string | null>;
    listSessions(options?: BackendSessionListOptions): Promise<BackendSessionListResult>;
    deleteBackendSession(sessionId: string, options?: {
        cwd?: string;
    }): Promise<boolean>;
    rewindToUserTurn(targetTurnIndex: number): Promise<BackendRewindResult>;
    renameBackendSession(sessionId: string, title: string, options?: {
        cwd?: string;
    }): Promise<boolean>;
    loadSessionMessages(sessionId: string, options?: {
        cwd?: string;
    }): Promise<BackendSessionMessagesResult>;
    refreshAvailableCommands(): Promise<AvailableCommandsSnapshot | null>;
    queryLlm(request: LLMQueryRequest): Promise<LLMQueryResult>;
    destroy(): void;
    private ensureProcess;
    private startProcess;
    private buildSpawnCommand;
    private handleExtMethod;
    private getAcpConnection;
    private callAcp;
    private withTimeout;
    private handleProcessExit;
    private killSubprocess;
    private registerAcpSession;
    private unregisterAcpSession;
    private ensureHopCodeSession;
    private createOrLoadHopCodeSession;
    private reloadCurrentSessionForAvailableCommands;
    private createEphemeralSession;
    private recordSessionModels;
    private isKnownAvailableModel;
    private getCurrentModelContextWindow;
    private applyCurrentModelContextWindow;
    private recordSessionModes;
    private forwardModel;
    private applySessionSettings;
    private forwardPermissionMode;
    private resolvedCwd;
    private extractHopCodeRecordText;
    private getHopCodeTranscriptPatchContent;
    private isPatchableHopCodeUserRecord;
    private persistHopCodeTranscriptTextElements;
    private readHopCodeTranscriptTextElements;
    private applyHopCodeTranscriptTextElements;
    private buildAcpMcpServers;
    private buildPromptBlocks;
    private buildCraftContext;
    private buildQueryPrompt;
    private handleSessionUpdate;
    private collectMiniUpdate;
    private buildHistoryMessages;
    private mergeHopCodeTranscriptTelemetryMessages;
    private loadHopCodeTranscriptTelemetryMessages;
    private extractHopCodeTranscriptToolResult;
    private buildHopCodeTranscriptTelemetryMessage;
    private resolveHopCodeTranscriptTelemetryParent;
    private mergeSlashCommandInvocationMessages;
    private isSameSlashCommandInvocationMessage;
    private loadSlashCommandInvocationMessages;
    private handleAgentMessageChunk;
    private handleAgentThoughtChunk;
    private flushPendingTextAsIntermediate;
    private flushThoughtText;
    private flushAssistantText;
    private handleToolCall;
    private handleToolCallUpdate;
    private handlePlanUpdate;
    private handleModeUpdate;
    private applyAcpPermissionMode;
    private parseAvailableCommandsUpdate;
    private extractAvailableCommandsSnapshot;
    private extractLatestTokenUsage;
    private handleAvailableCommandsUpdate;
    private handleOrStoreAvailableCommandsUpdate;
    private flushPendingAvailableCommandsUpdate;
    private waitForAvailableCommandsSnapshot;
    private resolveAvailableCommandsWaiters;
    private formatToolResult;
    private captureUsage;
    private captureUsageInto;
    private extractUsage;
    private handlePermissionRequest;
    private permissionImpact;
    private selectPermissionOption;
    private createPermissionResponse;
    private cancelPendingPermissions;
    private resolvePendingPermission;
    protected debug(message: string): void;
}
export { HopCodeAgent as HopCodeBackend };
